name: meik

volumes:
  sock:
  couchdb_data_persistent:
  mariadb_data_persistent:
  
services:
  app:
    profiles: [dev, prod, prod-ssr]
    build:
      context: app
      additional_contexts:
        python: ../python
      args:
        NORMAL_UID_GID: ${NORMAL_UID_GID}
    volumes:
      - sock:/run/php/fpm/sock
      - ../:/var/www
      - ../log/app:/var/log
      - ../python:/var/python/src
    restart: on-failure:2
  
  node:
    profiles: [dev, prod]
    build:
      context: node
      args:
        NORMAL_UID_GID: ${NORMAL_UID_GID}
    volumes:
      - ../:/var/www
  
  web:
    profiles: [dev, prod, prod-ssr]
    build:
      context: web
    volumes:
      - sock:/run/php/fpm/sock
      - ../:/var/www
      - ../log/web:/var/log
      - ./certificates:/certificates
    restart: on-failure:2
  
  db:
    profiles: [dev, prod, prod-ssr]
    build:
      context: db
    hostname: couchdb
    restart: on-failure:2
    volumes:
      - couchdb_data_persistent:/opt/couchdb/data
      - ../.env:/tmp/.env
  
  mariadb:
    profiles: [dev, prod, prod-ssr]
    image: mariadb:11.5.2-noble
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 0
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data_persistent:/var/lib/mysql
    restart: on-failure:2
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
  
  phpmyadmin:
    profiles: [dev]
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb
    ports:
      - 8081:80
    restart: on-failure:2
    depends_on:
      mariadb:
        condition: service_healthy
