name: meik

volumes:
  sock:

services:
  app:
    build:
      context: app
      args:
        UBUNTU_VERSION: 22.04
        PHP_VERSION: 8.3
    restart: unless-stopped
    volumes:
      - sock:/sock
      - ../:/var/www

  web:
    build:
      context: web
      args:
        NGINX_VERSION: 1.26.2
    volumes:
      - sock:/sock
