services:
  web:
    build:
      args:
        DOMAIN_NAME: meik-gr3.industrieschule.de
        PRIVATE_KEY_FILENAME: filename.key
        CERTIFICATE_FILENAME: filename.cer
    ports:
      - 443:443 # nur HTTPS
  
  # db:
  #   ports:
  #     - 5984:5984
