name: meik

volumes:
  sock:
  couchdb_data_persistent:
  mariadb_data_persistent:
  
services:
  app:
    build:
      context: app
      args:
        NORMAL_UID_GID: ${NORMAL_UID_GID}
    volumes:
      - sock:/run/php/fpm/sock
      - ../:/var/www
      - ../log/app:/var/log
    restart: on-failure:2
  
  node:
    build:
      context: node
      args:
        NORMAL_UID_GID: ${NORMAL_UID_GID}
    volumes:
      - ../:/var/www
    entrypoint: []
    command: ["npm", "run", "dev"]
  
  web:
    build:
      context: web
    ports:
      - 8080:80 # HTTP
      - 444:443 # HTTPS
    volumes:
      - sock:/run/php/fpm/sock
      - ../:/var/www
      - ../log/web:/var/log
    restart: on-failure:2
  
  db:
    build:
      context: db
    hostname: couchdb
    ports:
      - 5984:5984
    restart: on-failure:2
    volumes:
      - couchdb_data_persistent:/opt/couchdb/data

  mariadb:
    image: mariadb:11.5.2-noble
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 0
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data_persistent:/var/lib/mysql
    restart: on-failure:2
