services:
  web:
    build:
      args:
        DOMAIN_NAME: meik-gr3.industrieschule.de
        PRIVATE_KEY_FILENAME: filename.key
        CERTIFICATE_FILENAME: filename.cer
  
  # db:
  #   ports:
  #     - 5984:5984
