name: meik

volumes:
  sock:

services:
  app:
    build:
      context: app
    volumes:
      - sock:/sock
      - ../../:/var/www
    restart: on-failure:5
  
  web:
    build:
      context: web
    ports:
      - 8080:80
    volumes:
      - sock:/sock
    restart: on-failure:5
  
  db:
    build:
      context: db
    hostname: couchdb
    volumes:
      - ./db:/build_context
    ports:
      - 5984:5984
    restart: on-failure:1
