name: meik

volumes:
  sock:

services:
  app:
    build:
      context: app
    restart: unless-stopped
    volumes:
      - sock:/sock
      - ../:/var/www
      - ./app:/var/cache/getcomposer
  
  web:
    build:
      context: web
    ports:
      - 8080:80
    volumes:
      - sock:/sock
